-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GEN (ID, PARENT_ID, GENERATION) AS (
	SELECT ID, PARENT_ID, 1 AS GENERATION FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, EG.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_GEN EG ON E.PARENT_ID = EG.ID
)
SELECT ID FROM ECOLI_GEN
WHERE GENERATION = 3
ORDER BY ID;