WITH CAR_FEE AS (
    SELECT CAR_ID, C.CAR_TYPE, DISCOUNT_RATE, ROUND(C.DAILY_FEE * (1 - DP.DISCOUNT_RATE / 100) * 30, 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON C.CAR_TYPE = DP.CAR_TYPE
    WHERE C.CAR_TYPE IN ('SUV', '세단') AND DP.DURATION_TYPE = '30일 이상')

SELECT DISTINCT
    F.CAR_ID, 
    F.CAR_TYPE, 
    F.FEE
FROM CAR_FEE F
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    ON F.CAR_ID = RH.CAR_ID 
       AND (RH.START_DATE LIKE '2022-11%' AND RH.END_DATE LIKE '2022-11%')
WHERE 
	F.FEE BETWEEN 500000 AND 1999999
    AND NOT EXISTS (
        SELECT 1 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
        WHERE 
            RH.CAR_ID = F.CAR_ID
            AND RH.START_DATE <= DATE '2022-11-30'
            AND RH.END_DATE >= DATE '2022-11-01'
    )
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
