WITH RECURSIVE ECOLI_TREE AS (
  SELECT 
    ID, 
    PARENT_ID, 
    1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL
  UNION ALL
  SELECT 
    E.ID, 
    E.PARENT_ID, 
    ET.GENERATION + 1 AS GENERATION
  FROM ECOLI_DATA E
  JOIN ECOLI_TREE ET ON E.PARENT_ID = ET.ID
)
SELECT
	COUNT(*) AS COUNT,
    GENERATION
FROM ECOLI_TREE
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_TREE WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;