-- 코드를 작성해주세요
WITH EMP_GRADE AS (
    SELECT
    	EMP_NO,
    	CASE 
    		WHEN AVG(SCORE) >= 96 THEN 'S'
    		WHEN AVG(SCORE) >= 90 THEN 'A'
    		WHEN AVG(SCORE) >= 80 THEN 'B'
    		ELSE 'C'
    	END AS GRADE,
    	CASE
    		WHEN AVG(SCORE) >= 96 THEN 20
    		WHEN AVG(SCORE) >= 90 THEN 15
    		WHEN AVG(SCORE) >= 80 THEN 10
    		ELSE 0
    	END AS PERC
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT
	E.EMP_NO,
    EMP_NAME,
    GRADE,
    IF(PERC = 0, 0, SAL / 100 * PERC) AS BONUS
FROM HR_EMPLOYEES E
JOIN EMP_GRADE G ON E.EMP_NO = G.EMP_NO;
