-- 코드를 입력하세요
WITH FOOD_RANK AS (
    SELECT
    	CATEGORY,
    	PRICE,
    	PRODUCT_NAME,
    	ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS rn
    FROM FOOD_PRODUCT
	WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT
	CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM FOOD_RANK
WHERE rn = 1
ORDER BY MAX_PRICE DESC;
